# Numpy and vectorization
* [numpy documentation](https://numpy.org/doc/stable/reference/index.html)
* [Array broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html)

In [1]:
import numpy as np

## Useful math functions

In [2]:
print(np.exp(1))
print(np.sin(np.pi/3))

2.718281828459045
0.8660254037844386


## Making some arrays

In [13]:
ones = np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


In [3]:
odd = np.arange(3,31,2)
print(odd)

[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29]


In [4]:
z2y = np.linspace(0, 1, 11)
print(z2y)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [5]:
ary_2D = np.array([[1, 2, 3], [4, 5, 6]])
print(ary_2D)

[[1 2 3]
 [4 5 6]]


Random numbers

In [9]:
rand_mat = np.random.normal(0, 1, size=(3,3))
print(rand_mat)

[[ 2.0834725  -0.33008264  1.46663307]
 [-0.37787599 -1.11219928 -0.2113888 ]
 [-0.93974859 -0.48106454  0.58445781]]


## Array indexing and slicing

In [14]:
print(odd)
print(odd[-2])
print(odd[1:10])
print(odd[1:-1:2])

[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29]
27
[ 5  7  9 11 13 15 17 19 21]
[ 5  9 13 17 21 25]


In [15]:
print(rand_mat)
print(rand_mat[1,1])
print(rand_mat[1,:])

[[ 2.0834725  -0.33008264  1.46663307]
 [-0.37787599 -1.11219928 -0.2113888 ]
 [-0.93974859 -0.48106454  0.58445781]]
-1.1121992754996801
[-0.37787599 -1.11219928 -0.2113888 ]


## Array attributes and method

In [40]:
rand_mat.shape

(3, 3)

In [41]:
rand_mat.size

9

In [ ]:
# transpose

print(ary_2D)
print(ary_2D.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [18]:
print(rand_mat.ravel())

[ 2.0834725  -0.33008264  1.46663307 -0.37787599 -1.11219928 -0.2113888
 -0.93974859 -0.48106454  0.58445781]


## Array operations

In [19]:
rand_mat_1 = np.random.normal(0, 1, size=(2,3))
rand_mat_2 = np.random.normal(0, 1, size=(2,3))

In [20]:
print(rand_mat_1+rand_mat_2)

[[ 0.05977354  2.33212057  3.7291422 ]
 [ 1.20587948 -1.88274915  0.04751487]]


In [21]:
print(rand_mat_1*rand_mat_2)

[[-0.4488452   1.21911392  3.43584622]
 [ 0.30391829  0.6204603  -1.56250322]]


In [23]:
print(rand_mat_1@rand_mat_2.T)

[[ 4.20611494  0.63899735]
 [-2.91887063 -0.63812463]]


In [25]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
x = np.linalg.solve(a, b)

print(x)

[-1.  1.]


In [26]:
print(ary_2D)
print(ary_2D.mean(axis=1))

[[1 2 3]
 [4 5 6]]
[2. 5.]


## Vectorized operations are much faster than loops!

In [28]:
import time

ary_1 = np.random.normal(0, 1, size=10000000)
ary_2 = np.random.normal(0, 1, size=10000000)

In [29]:
dot_prod = 0

t0 = time.time()

for i in range(ary_1.size):
    dot_prod += ary_1[i]*ary_2[i]

t1 = time.time()
print("Result is: %.3e" %dot_prod)
print("Calculation took: %.3e" %(t1-t0))

Result is: 1.797e+03
Calculation took: 2.983e+00


In [30]:
t0 = time.time()

dot_prod_vec = ary_1@ary_2.T

t1 = time.time()
print("Result is: %.3e" %dot_prod_vec)
print("Calculation took: %.3e" %(t1-t0))

Result is: 1.797e+03
Calculation took: 1.428e-02


## Be mindful of shallow copy
A common source of mistake, annoying to debug

In [73]:
ary_1 = np.ones(10)
print(ary_1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [75]:
ary_shallow = ary_1
ary_shallow[1] = 10

print(ary_shallow)
print(ary_1)

[ 1. 10.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1. 10.  1.  1.  1.  1.  1.  1.  1.  1.]


In [76]:
ary_deep = np.copy(ary_1)
ary_deep[-1] = 10

print(ary_deep)
print(ary_1)

[ 1. 10.  1.  1.  1.  1.  1.  1.  1. 10.]
[ 1. 10.  1.  1.  1.  1.  1.  1.  1.  1.]
