In [34]:
import numpy as np
import matplotlib

In [35]:
A = np.random.normal(0, 1, (10,10))
v0 = np.random.normal(0, 1, 10)

A = A+A.T

In [36]:
print(A)

[[ 0.5546711   0.25741367  0.60334369  0.76426536 -0.67431882 -1.23026966
   0.43423903  2.8663285  -0.47586665  1.5949422 ]
 [ 0.25741367 -3.90265393 -1.4837838  -2.60772309  3.71289022 -0.53561384
   0.26749774 -1.01741184  0.72648493 -0.70795655]
 [ 0.60334369 -1.4837838  -0.24809823  1.04694915  3.11157324 -0.83335823
   0.32907419  2.93065036 -1.01620014  1.46468325]
 [ 0.76426536 -2.60772309  1.04694915 -2.83270934  0.57610375  1.33910602
   1.07666825 -0.66767774  1.89548546  0.62239372]
 [-0.67431882  3.71289022  3.11157324  0.57610375 -0.50124701  1.10708825
   0.59731916 -0.53008094  0.86183642 -0.64533252]
 [-1.23026966 -0.53561384 -0.83335823  1.33910602  1.10708825 -3.00315633
   0.43997043 -1.8479824   0.01931239 -1.56661256]
 [ 0.43423903  0.26749774  0.32907419  1.07666825  0.59731916  0.43997043
   0.6048508   3.31106396 -0.21875407  1.83823981]
 [ 2.8663285  -1.01741184  2.93065036 -0.66767774 -0.53008094 -1.8479824
   3.31106396  0.26270573  0.51826515 -0.16508376]
 

In [42]:
[l,VV]=np.linalg.eig(A)

In [47]:
v_tru = VV[:,0]

In [48]:
A@v_tru/v_tru

array([7.23813322, 7.23813322, 7.23813322, 7.23813322, 7.23813322,
       7.23813322, 7.23813322, 7.23813322, 7.23813322, 7.23813322])

In [70]:
def ray_quo(A,v):
    return v.T@A@v

In [85]:
lamb_iter_ary = np.empty(8)
verr_iter_ary = np.ones(8)

v_iter = v0
# lamb_iter = ray_quo(A,v0)
lamb_iter = 5

for i in range(8):
    lamb_iter_ary[i] = lamb_iter
    verr = min(np.sqrt((v_iter-v_tru).T@(v_iter-v_tru)),np.sqrt((-v_iter-v_tru).T@(-v_iter-v_tru)))
    verr_iter_ary[i] = verr
    # print(np.sqrt((v_iter-v_tru).T@(v_iter-v_tru)))
    
    v_iter = np.linalg.solve((A-lamb_iter*np.eye(10)),v_iter )
    v_iter = v_iter/np.sqrt(v_iter.T@v_iter)
    lamb_iter = ray_quo(A,v_iter)

In [86]:
lamb_iter_ary

array([5.        , 5.2487159 , 6.9181105 , 7.23729494, 7.23813322,
       7.23813322, 7.23813322, 7.23813322])

In [87]:
verr_iter_ary

array([2.25683009e+00, 5.16670289e-01, 2.15768552e-01, 1.17438074e-02,
       1.82597664e-06, 5.97435970e-16, 5.40009833e-16, 5.32616610e-16])